-- removing these because of varisous reasons
return {
	-- too heavy for large projects
	-- {
	-- 	"lukas-reineke/indent-blankline.nvim",
	-- 	main = "ibl",
	-- 	opts = {},
	-- },
	-- inocrrec indents
	-- {
	-- 	"nvimdev/indentmini.nvim",
	-- 	config = function()
	-- 		require("indentmini").setup({
	-- 			only_current = true, -- Highlight only the current scope
	-- 		})
	-- 	end,
	-- },
	-- only used in python to select virtual env
	-- "linux-cultist/venv-selector.nvim",
	-- dependencies = {
	-- 	"neovim/nvim-lspconfig",
	-- 	"mfussenegger/nvim-dap",
	-- 	"mfussenegger/nvim-dap-python", --optional
	-- 	{ "nvim-telescope/telescope.nvim", branch = "0.1.x", dependencies = { "nvim-lua/plenary.nvim" } },
	-- },
	-- lazy = false,
	-- branch = "regexp", -- This is the regexp branch, use this for the new version
	-- config = function()
	-- 	require("venv-selector").setup()
	-- end,
	-- event = "VeryLazy", -- Optional: needed only if you want to type `:VenvSelect` without a keymapping
	-- keys = {
	-- 	{ "<leader>vs", "<cmd>VenvSelect<cr>", desc = "Open venv for python" },
	-- 	{ "<leader>vc", "<cmd>VenvSelectCached<cr>", desc = "Retrieve venv from cache for python" },
	-- },
	-- Never really used it actually. Learning to use harpoon.
	-- {
	-- 	"szw/vim-maximizer",
	-- 	keys = {
	-- 		{ "<leader>sm", "<cmd>MaximizerToggle<CR>", desc = "Maximize/minimize a split" },
	-- 	},
	-- },
}
