general.import = ["~/.config/alacritty/themes/night_owl.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 17.0

[font.bold]
family = "BlexMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "BlexMono Nerd Font"
style = "SemiBold Italic"

[font.italic]
family = "BlexMono Nerd Font"
style = "Italic"

[font.normal]
family = "BlexMono Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
# Available values:
  # - full: borders and title bar
  # - none: neither borders nor title bar
  # - transparent: title bar, transparent background and title bar buttons
  # - buttonless: title bar, transparent background, but no title bar buttons
dynamic_padding = false
opacity = 0.88 # 0 to 1
blur = true
decorations_theme_variant = "Dark" # "Dark", "Light", "None" <- default

[window.padding]
# spacing around the window 
x = 5 
# y = 10 

[window.dimensions]
columns = 150
lines = 57 

