format = """$sudo$username$hostname$directory$git_branch$git_commit$git_state$git_status\
$os$python$nodejs$docker_context$golang$time\
$jobs$status$cmd_duration\
$fill\
\n$character"""

[directory]
style = '#FF7F50'

[character]
success_symbol = '[󱞩](bold green)'
error_symbol = '[󱞩](bold red)'

[cmd_duration]
min_time = 5_00
show_milliseconds = true
format = '[$duration](bold yellow)'

[fill]
symbol = ' '

[git_branch]
style = '#008080'
