[opener]
edit = [
{ run = 'nvim "$@"', block = true },
{ run = 'zed "$@"', block = true},
{ run = 'code "$@"', block = true},
]

[mgr]
layout         = [ 2, 4, 3 ]
sort_by        = "mtime"
sort_sensitive = false
sort_reverse   = true
sort_dir_first = true
show_hidden    = true 
show_symlink   = true
